// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/CinematicHero.tsx": () => import("../components/mockups/hero-variants/CinematicHero.tsx"),
  "./components/mockups/hero-variants/SplitReverseHero.tsx": () => import("../components/mockups/hero-variants/SplitReverseHero.tsx"),
  "./components/mockups/hero-variants/StackedHero.tsx": () => import("../components/mockups/hero-variants/StackedHero.tsx")
};
